name: Issue Release Workflow

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  backport-commits:
    name: Backport Commits
    runs-on: ubuntu-latest
    if: >-
        contains(github.event.comment.body, '/cherry-pick')

    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          fetch-depth: 0

      - name: Setup Environment
        run: |
          #FIXME: TEMP
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/requirements.txt
          chmod a+x github-automation.py
          #FIXME
          pip install -r requirements.txt
          ./github-automation.py --token ${{ github.token }} setup-llvmbot-git

      - name: Backport Commits
        run: |
          printf "${{ github.event.comment.body }}" |
          ./github-automation.py \
          --repo $GITHUB_REPOSITORY \
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-workflow \
          --issue-number ${{ github.event.issue.number }} \
          --branch-repo $GITHUB_REPOSITORY \
          auto

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: >-
        contains(github.event.comment.body, '/branch')

    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v2

      - name: Setup Environment
        run:  |
          pip install -r ./llvm/utils/git/requirements.txt

      - name: Create Pull Request
        run: |
          printf "${{ github.event.comment.body }}" |
          ./llvm/utils/git/github-automation.py \
          --repo $GITHUB_REPOSITORY \
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-workflow \
          --issue-number ${{ github.event.issue.number }} \
          --branch-repo $GITHUB_REPOSITORY \
          auto
